const MemoCardList = [

    { src: require('../../../../Images/memo-icons/ace_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/2_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/3_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/4_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/5_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/6_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/7_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/8_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/9_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/10_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/jack_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/queen_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/king_of_spades.png'), matched: false },
    { src: require('../../../../Images/memo-icons/ace_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/2_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/3_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/4_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/5_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/6_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/7_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/8_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/9_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/10_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/jack_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/queen_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/king_of_hearts.png'), matched: false },
    { src: require('../../../../Images/memo-icons/ace_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/2_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/3_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/4_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/5_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/6_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/7_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/8_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/9_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/10_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/jack_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/queen_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/king_of_diamonds.png'), matched: false },
    { src: require('../../../../Images/memo-icons/ace_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/2_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/3_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/4_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/5_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/6_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/7_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/8_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/9_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/10_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/jack_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/queen_of_clubs.png'), matched: false },
    { src: require('../../../../Images/memo-icons/king_of_clubs.png'), matched: false },
];



export default MemoCardList;